# Generated by Django 4.2.30 on 2026-05-22 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recovery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('PHONE_CALL', 'Phone Call'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('GROUP_MEETING', 'Group Meeting'), ('FIELD_VISIT', 'Field Visit'), ('DEMAND_LETTER', 'Demand Letter'), ('PROMISE_TO_PAY', 'Promise to Pay'), ('ESCALATION', 'Escalation'), ('LEGAL_ACTION', 'Legal Action')], max_length=30)),
                ('notes', models.TextField()),
                ('result', models.TextField(blank=True)),
                ('promise_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('promise_date', models.DateField(blank=True, null=True)),
                ('next_action_date', models.DateField(blank=True, null=True)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='followups/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow_ups', to=settings.AUTH_USER_MODEL)),
                ('recovery_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='recovery.recoverycase')),
            ],
            options={
                'verbose_name': 'Follow-up Action',
                'verbose_name_plural': 'Follow-up Actions',
                'ordering': ['-created_at'],
            },
        ),
    ]
