# Generated by Django 4.2.30 on 2026-05-22 10:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowers', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_number', models.CharField(max_length=50, unique=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('days_overdue', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('OVERDUE', 'Overdue'), ('PAID', 'Paid'), ('DEFAULTED', 'Defaulted')], default='ACTIVE', max_length=20)),
                ('disbursement_date', models.DateField()),
                ('last_repayment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='borrowers.borrower')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='groups.group')),
            ],
            options={
                'ordering': ['-disbursement_date'],
            },
        ),
    ]
