# Generated by Django 4.2.30 on 2026-05-22 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(max_length=50, unique=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACT_ATTEMPT', 'Contact Attempt'), ('PROMISE_TO_PAY', 'Promise to Pay'), ('PARTIAL_RECOVERY', 'Partial Recovery'), ('FIELD_VISIT', 'Field Visit'), ('ESCALATED', 'Escalated'), ('LEGAL_REVIEW', 'Legal Review'), ('CLOSED', 'Closed')], default='NEW', max_length=30)),
                ('escalation_level', models.IntegerField(default=0)),
                ('next_action_date', models.DateField(blank=True, null=True)),
                ('promise_to_pay_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('promise_to_pay_date', models.DateField(blank=True, null=True)),
                ('total_collected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recovery_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_case', to='loans.loan')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
    ]
