# Generated by Django 4.2.30 on 2026-05-22 10:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=100)),
                ('chairperson', models.CharField(max_length=255)),
                ('active_members', models.PositiveIntegerField(default=0)),
                ('total_arrears', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('recovery_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
